remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Shadows in the Sun - A guilty secret in a busy city]
description: [An analytics app based on the Chicago crime dataset]